"""Visual document search + question answering, vision end-to-end.

The whole pipeline is Qwen-family and never collapses a page through OCR:

  1. encode(ColQwen2.5, text)                  — query multivector
  2. sie_sdk.scoring.maxsim                     — late interaction against page images
  3. score(Qwen3-VL-Reranker, query, images)    — optional second stage, off by default
  4. Qwen3.5-4B (vision) via /v1/chat/completions — reads the winning page image
                                                  and answers the question

The ranking is decided by a vision model looking at the page image, so charts,
schematics, pinout diagrams, scanned engineering drawings, and any other layout
cue that an OCR round-trip would erase still contributes to the score. The
answer step also reads the page as an image, so the page never has to have a
text layer at all.

Multi-tenant isolation is a Python filter on metadata before MaxSim, so a
query scoped to one client never sees another client's pages.
"""

from __future__ import annotations

import base64
import json
import os
import time
from pathlib import Path

import httpx
import numpy as np
import yaml

from sie_sdk import SIEClient
from sie_sdk.scoring import maxsim
from sie_sdk.types import Item


def load_config():
    return yaml.safe_load((Path(__file__).resolve().parent.parent / "config.yaml").read_text())


def load_index():
    data_dir = Path(__file__).resolve().parent.parent / "data"
    if not (data_dir / "multivectors.npz").exists():
        raise FileNotFoundError("data/multivectors.npz missing. Run `python python/ingest.py` first.")
    npz = np.load(data_dir / "multivectors.npz")
    metadata = json.loads((data_dir / "metadata.json").read_text())
    required = {"page_id", "client", "source_pdf", "page_number", "image_path", "publisher", "source_url"}
    if metadata:
        missing = required - set(metadata[0])
        if missing:
            raise ValueError(
                "data/metadata.json was generated by an older corpus shape. "
                "Run `python data/fetch_pdfs.py`, `python data/render_pages.py`, "
                "then `python python/ingest.py`."
            )
    multivectors = {m["page_id"]: npz[m["page_id"]] for m in metadata}
    return multivectors, metadata


_ANSWER_SYSTEM = (
    "You are shown one page of a document as an image and a question about it. "
    "Answer with the shortest exact value, name, or phrase taken from the page — "
    "no explanation. If the page does not contain the answer, reply exactly: "
    "not shown on this page."
)


def _vqa_answer(
    cluster_url: str,
    api_key: str,
    model: str,
    question: str,
    image_path: str,
    provision_timeout_s: float,
) -> str:
    """Answer a question about one page image with a vision LLM.

    Qwen3.5-4B is a vision+text generation model, so it reads the page image
    directly. SIE exposes generation through the OpenAI-compatible
    `/v1/chat/completions` endpoint (the SIE SDK's `generate()` is text-only),
    so this is a plain multimodal chat call rather than an SDK method.
    """
    data = base64.b64encode(Path(image_path).read_bytes()).decode()
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": _ANSWER_SYSTEM},
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": question},
                    {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{data}"}},
                ],
            },
        ],
        "max_tokens": 64,
        "temperature": 0.0,
    }
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    # The generation bundle can scale from zero. While it provisions, the
    # gateway may answer 202/503 ("still loading") or hold the connection until
    # it times out; retry both under the provisioning budget, like the SDK does.
    deadline = time.time() + provision_timeout_s
    while True:
        try:
            resp = httpx.post(f"{cluster_url}/v1/chat/completions", json=payload, headers=headers, timeout=120.0)
        except httpx.TransportError:
            if time.time() < deadline:
                time.sleep(5)
                continue
            raise
        if resp.status_code in (202, 503) and time.time() < deadline:
            time.sleep(5)
            continue
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"].strip()


def search(
    client: SIEClient,
    config: dict,
    multivectors: dict[str, np.ndarray],
    metadata: list[dict],
    query: str,
    client_filter: str | None = None,
) -> dict:
    gpu = config["cluster"]["gpu"]
    timeout = config["cluster"]["provision_timeout_s"]
    top_k_candidates = config["search"]["top_k_candidates"]
    top_k_results = config["search"]["top_k_results"]
    do_visual_rerank = config["search"].get("visual_rerank", False)
    do_answer = config["search"].get("answer", True)
    answer_url = os.environ.get("SIE_CLUSTER_URL", config["cluster"]["url"])
    answer_key = os.environ.get("SIE_API_KEY", config["cluster"]["api_key"])

    corpus = [m for m in metadata if not client_filter or m["client"] == client_filter]
    if not corpus:
        return {"results": [], "answer": None, "timings": {}}

    timings: dict[str, float] = {}
    pages_root = Path(__file__).resolve().parent.parent / "data"

    # 1. Encode query (text side of ColQwen2.5).
    t0 = time.time()
    q_result = client.encode(
        config["models"]["retriever"],
        Item(text=query),
        output_types=["multivector"],
        is_query=True,
        gpu=gpu,
        wait_for_capacity=True,
        provision_timeout_s=timeout,
    )
    timings["encode_query_s"] = round(time.time() - t0, 3)
    query_mv = q_result["multivector"].astype(np.float32)

    # 2. MaxSim against in-memory multivectors.
    doc_mvs = [multivectors[m["page_id"]] for m in corpus]
    t0 = time.time()
    maxsim_scores = maxsim(query_mv, doc_mvs)
    timings["maxsim_s"] = round(time.time() - t0, 3)

    order = np.argsort(maxsim_scores)[::-1][:top_k_candidates]
    candidates: list[dict] = []
    for idx in order:
        c = dict(corpus[idx])
        c["_maxsim_score"] = float(maxsim_scores[idx])
        c["_rerank_score"] = None
        candidates.append(c)

    # 3. Optional visual rerank. Image-in cross-encoder so OCR never enters the
    #    ranking path. Off by default; see config.yaml for what a deployment
    #    needs to serve it.
    if do_visual_rerank and candidates:
        try:
            t0 = time.time()
            rerank_items = [
                Item(id=c["page_id"], images=[str(pages_root / c["image_path"])])
                for c in candidates
            ]
            rerank = client.score(
                config["models"]["reranker"],
                Item(text=query),
                rerank_items,
                gpu=gpu,
                wait_for_capacity=True,
                provision_timeout_s=timeout,
            )
            timings["visual_rerank_s"] = round(time.time() - t0, 3)
            rerank_by_id = {s["item_id"]: s for s in rerank["scores"]}
            for c in candidates:
                s = rerank_by_id.get(c["page_id"])
                c["_rerank_score"] = float(s["score"]) if s else 0.0
            candidates.sort(key=lambda c: c["_rerank_score"] or 0.0, reverse=True)
        except Exception as exc:
            # If the deployment can't serve the reranker, keep the MaxSim
            # ordering and surface the failure to the caller.
            timings["visual_rerank_error"] = type(exc).__name__

    results = candidates[:top_k_results]

    # 4. Answer from the top page image with the Qwen3.5-4B vision model. It
    #    reads the page as an image, so the answer survives even on a scanned
    #    page with no text layer.
    answer = None
    if do_answer and results:
        top = results[0]
        try:
            t0 = time.time()
            answer = _vqa_answer(
                answer_url,
                answer_key,
                config["models"]["answer"],
                query,
                str(pages_root / top["image_path"]),
                timeout,
            )
            timings["answer_s"] = round(time.time() - t0, 3)
        except Exception as exc:
            timings["answer_error"] = type(exc).__name__

    return {"results": results, "answer": answer, "timings": timings}


def print_run(out: dict, query: str, client_filter: str | None):
    scope = client_filter or "all clients"
    print(f'\n  Query: "{query}"  ({scope})')
    print(f"  Timings: {out['timings']}")
    if out["answer"]:
        print(f"\n  Answer: {out['answer']}")
    if not out["results"]:
        print("  No results.")
        return
    for i, r in enumerate(out["results"], 1):
        rerank = r.get("_rerank_score")
        rerank_str = f"rerank={rerank:.4f}" if rerank is not None else "rerank=—"
        print(f"\n  {i}. [{r['client']}] {r['title']}")
        print(f"     {r['source_pdf']}  ·  p.{r['page_number']}  ·  {r['publisher']}")
        print(f"     maxsim={r['_maxsim_score']:.3f}  {rerank_str}")
        print(f"     url: {r['source_url']}")


def main():
    config = load_config()
    multivectors, metadata = load_index()
    print(f"Loaded index: {len(metadata)} pages")

    cluster_url = os.environ.get("SIE_CLUSTER_URL", config["cluster"]["url"])
    api_key = os.environ.get("SIE_API_KEY", config["cluster"]["api_key"])

    demo = [
        # Read a value straight off a dense config page.
        ("What is the default TCP port a PostgreSQL server listens on?", "ops-eng"),
        ("What is the default value of max_connections in PostgreSQL?", "ops-eng"),
        # Read a spec off a hardware datasheet.
        ("What is the GPIO (IO) voltage of the Raspberry Pi Pico?", "embedded-lab"),
        # Scanned engineering drawing: the page has no text layer, so only the
        # visual retrieval finds it — and the vision model still reads the figure.
        ("What does Figure 7 in the solid rocket motor nozzle report show?", "aerospace"),
        # No tenant filter: the question routes to the right tenant on its own.
        ("Which Arduino UNO datasheet section covers the power tree?", None),
        # Disambiguation: regenerative cooling is liquid-specific, so the liquid
        # report must win over the solid one in the same aerospace tenant.
        ("regeneratively cooled nozzle", "aerospace"),
        # Tenant isolation: that content lives in aerospace; scoped to ops-eng it
        # must surface zero aerospace pages.
        ("regeneratively cooled nozzle", "ops-eng"),
    ]
    with SIEClient(cluster_url, api_key=api_key) as client:
        for query, tenant in demo:
            out = search(client, config, multivectors, metadata, query, tenant)
            print_run(out, query, tenant)


if __name__ == "__main__":
    main()
