//! Rust ↔ Python AutoTokenizer byte-identity harness.
//!
//! The goal of this test is to prove that
//! [`sie_server_sidecar::tokenize::tokenize_no_pad`] produces byte-for-byte
//! identical `input_ids`, `attention_mask`, and `token_type_ids` to
//! Python's `transformers.AutoTokenizer(..., padding=False,
//! truncation=True, max_length=N)` for a given real-world tokenizer
//! (in practice: `Alibaba-NLP/gte-multilingual-base`).
//!
//! Running cost and offline constraints mean we do **not** ship the
//! real tokenizer weights in this repo. Instead the test is driven
//! by a fixture JSON file generated by the companion helper script
//! `packages/sie_server/scripts/generate_tokenize_fixture.py`, which
//! uses the real `transformers` library to produce ground-truth
//! token ids for a curated list of test cases.
//!
//! Usage:
//!
//! ```bash
//! # one-off: generate the fixture against the real HF tokenizer
//! uv run --with transformers --with huggingface_hub \
//!     packages/sie_server/scripts/generate_tokenize_fixture.py \
//!     --model Alibaba-NLP/gte-multilingual-base \
//!     --max-seq-len 512 \
//!     --out /tmp/gte_fixture.json
//!
//! # run the parity check
//! SIE_BYTE_IDENTITY_FIXTURE=/tmp/gte_fixture.json \
//!     cargo test --test byte_identity -- --nocapture
//! ```
//!
//! When `SIE_BYTE_IDENTITY_FIXTURE` is unset (the CI default) the
//! test is skipped with an informative log line so `cargo test`
//! stays green on developer machines that don't have the model
//! cached.

use std::path::PathBuf;

use serde::Deserialize;
use sie_server_sidecar::tokenize::{load_no_pad_tokenizer, tokenize_no_pad};

#[derive(Debug, Deserialize)]
struct Fixture {
    /// Human-readable identifier, e.g. "Alibaba-NLP/gte-multilingual-base".
    /// Not used by the test logic; purely for diagnostics.
    #[serde(default)]
    model_id: String,
    /// Absolute path to the `tokenizer.json` file used to produce
    /// the expected ids. The Rust side loads the same file.
    tokenizer_path: String,
    max_seq_len: usize,
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    text: String,
    /// Token ids produced by `transformers.AutoTokenizer(...,
    /// padding=False, truncation=True, max_length=N)`.
    input_ids: Vec<u32>,
    /// Attention mask as returned by the Python tokenizer. For the
    /// `padding=False` path this is always all-ones of length
    /// `input_ids.len()`, but we compare it verbatim anyway so a
    /// future change (e.g. bucket padding) would fail loudly.
    attention_mask: Vec<u32>,
    /// `token_type_ids` as returned by the Python tokenizer. Some
    /// tokenizers (e.g. XLM-R / gte-multilingual-base) don't emit
    /// these, and the Python `transformers` helper omits the field;
    /// the fixture generator represents that as an empty list.
    #[serde(default)]
    token_type_ids: Vec<u32>,
}

fn load_fixture() -> Option<Fixture> {
    let path = std::env::var("SIE_BYTE_IDENTITY_FIXTURE").ok()?;
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("SIE_BYTE_IDENTITY_FIXTURE={path} not readable: {e}"));
    let fixture: Fixture = serde_json::from_slice(&bytes).unwrap_or_else(|e| {
        panic!("SIE_BYTE_IDENTITY_FIXTURE={path} is not valid fixture JSON: {e}")
    });
    Some(fixture)
}

#[test]
fn rust_tokenize_matches_python_autotokenizer_byte_for_byte() {
    let Some(fixture) = load_fixture() else {
        eprintln!(
            "skipping byte-identity test: set SIE_BYTE_IDENTITY_FIXTURE=/path/to/fixture.json \
             (see tests/byte_identity.rs for how to generate one)"
        );
        return;
    };

    let tok_path = PathBuf::from(&fixture.tokenizer_path);
    assert!(
        tok_path.exists(),
        "fixture's tokenizer_path does not exist on disk: {}",
        tok_path.display()
    );

    let tokenizer = load_no_pad_tokenizer(&tok_path, fixture.max_seq_len)
        .expect("failed to load tokenizer.json on the Rust side");

    // Tokenise each case individually. We deliberately do NOT batch
    // them through one `encode_batch` call: the fixture generator
    // calls the Python tokenizer per-text as well, and we want to
    // preserve that semantics (no cross-sequence pair encoding).
    let mut mismatches: Vec<String> = Vec::new();

    for (i, case) in fixture.cases.iter().enumerate() {
        let got = tokenize_no_pad(&tokenizer, &[&case.text])
            .expect("tokenize_no_pad should not fail on well-formed input");
        assert_eq!(
            got.len(),
            1,
            "expected exactly one encoded sequence per call"
        );

        let got_ids = &got.input_ids[0];
        let got_mask = &got.attention_mask[0];
        let got_types = &got.token_type_ids[0];

        if *got_ids != case.input_ids {
            mismatches.push(format!(
                "case #{i} input_ids mismatch\n  text    = {:?}\n  python  = {:?}\n  rust    = {:?}",
                case.text, case.input_ids, got_ids
            ));
            continue;
        }

        if *got_mask != case.attention_mask {
            mismatches.push(format!(
                "case #{i} attention_mask mismatch\n  text    = {:?}\n  python  = {:?}\n  rust    = {:?}",
                case.text, case.attention_mask, got_mask
            ));
            continue;
        }

        // token_type_ids: some tokenizers (XLM-R family) don't emit
        // segment ids. The fixture encodes "not emitted" as an empty
        // list; in that case Rust's vector of zeros must also be all
        // zero (length match against input_ids is already implied by
        // the tokenizers crate contract).
        if case.token_type_ids.is_empty() {
            if got_types.iter().any(|&x| x != 0) {
                mismatches.push(format!(
                    "case #{i} token_type_ids: python emitted none but rust has non-zero segment ids\n  text = {:?}\n  rust = {:?}",
                    case.text, got_types
                ));
            }
        } else if *got_types != case.token_type_ids {
            mismatches.push(format!(
                "case #{i} token_type_ids mismatch\n  text    = {:?}\n  python  = {:?}\n  rust    = {:?}",
                case.text, case.token_type_ids, got_types
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} / {} case(s) differ from Python AutoTokenizer (model={}):\n\n{}",
        mismatches.len(),
        fixture.cases.len(),
        fixture.model_id,
        mismatches.join("\n\n")
    );

    eprintln!(
        "byte-identity: {} case(s) matched Python AutoTokenizer for {}",
        fixture.cases.len(),
        fixture.model_id
    );
}
