{{/*
Expand the name of the chart.
*/}}
{{- define "sie-cluster.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "sie-cluster.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "sie-cluster.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "sie-cluster.labels" -}}
helm.sh/chart: {{ include "sie-cluster.chart" . }}
{{ include "sie-cluster.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "sie-cluster.selectorLabels" -}}
app.kubernetes.io/name: {{ include "sie-cluster.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/part-of: sie
{{- end }}

{{/*
Gateway labels
*/}}
{{- define "sie-cluster.gateway.labels" -}}
{{ include "sie-cluster.labels" . }}
app.kubernetes.io/component: gateway
{{- end }}

{{/*
Gateway selector labels
*/}}
{{- define "sie-cluster.gateway.selectorLabels" -}}
{{ include "sie-cluster.selectorLabels" . }}
app.kubernetes.io/component: gateway
{{- end }}

{{/*
Config service labels
*/}}
{{- define "sie-cluster.config.labels" -}}
{{ include "sie-cluster.labels" . }}
app.kubernetes.io/component: config
{{- end }}

{{/*
Config service selector labels
*/}}
{{- define "sie-cluster.config.selectorLabels" -}}
{{ include "sie-cluster.selectorLabels" . }}
app.kubernetes.io/component: config
{{- end }}

{{/*
Worker labels
*/}}
{{- define "sie-cluster.worker.labels" -}}
{{ include "sie-cluster.labels" . }}
app.kubernetes.io/component: worker
{{- end }}

{{/*
Worker selector labels for a specific pool
*/}}
{{- define "sie-cluster.worker.selectorLabels" -}}
{{ include "sie-cluster.selectorLabels" . }}
app.kubernetes.io/component: worker
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "sie-cluster.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "sie-cluster.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Namespace to use
*/}}
{{- define "sie-cluster.namespace" -}}
{{- default .Release.Namespace .Values.global.namespace }}
{{- end }}

{{/*
Prometheus service generated by the kube-prometheus-stack sub-chart.
Mirrors kube-prometheus-stack's fullname helper truncation and service suffix.
*/}}
{{- define "sie-cluster.kubePrometheusStack.fullname" -}}
{{- $values := (index .Values "kube-prometheus-stack") | default dict -}}
{{- if $values.fullnameOverride -}}
{{- $values.fullnameOverride | trunc 26 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default "kube-prometheus-stack" $values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 26 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 26 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end }}

{{- define "sie-cluster.kubePrometheusStack.prometheusServiceName" -}}
{{- printf "%s-prometheus" (include "sie-cluster.kubePrometheusStack.fullname" .) -}}
{{- end }}

{{- define "sie-cluster.kubePrometheusStack.prometheusAddress" -}}
{{- printf "http://%s.%s.svc.cluster.local:9090" (include "sie-cluster.kubePrometheusStack.prometheusServiceName" .) (include "sie-cluster.namespace" .) -}}
{{- end }}

{{/*
Gateway image
*/}}
{{- define "sie-cluster.gateway.image" -}}
{{- $tag := default .Chart.AppVersion .Values.gateway.image.tag }}
{{- printf "%s:%s" .Values.gateway.image.repository $tag }}
{{- end }}

{{/*
Config service image
*/}}
{{- define "sie-cluster.config.image" -}}
{{- $tag := default .Chart.AppVersion .Values.config.image.tag }}
{{- printf "%s:%s" .Values.config.image.repository $tag }}
{{- end }}

{{/*
Config service resource name (Deployment / Service)
*/}}
{{- define "sie-cluster.config.serviceName" -}}
{{- $fullname := include "sie-cluster.fullname" . }}
{{- printf "%s-config" $fullname }}
{{- end }}

{{/*
In-cluster URL used by the gateway to reach the config service for the
bootstrap GET /v1/configs/export call and the periodic GET /v1/configs/epoch
drift poll. Built from the Helm-owned Service name and port so it stays
correct on overlays.
*/}}
{{- define "sie-cluster.config.internalUrl" -}}
{{- $svc := include "sie-cluster.config.serviceName" . }}
{{- $ns := include "sie-cluster.namespace" . }}
{{- $port := .Values.config.service.port | default 8080 }}
{{- printf "http://%s.%s.svc.cluster.local:%v" $svc $ns $port }}
{{- end }}

{{/*
Worker StatefulSet name for a pool
*/}}
{{- define "sie-cluster.worker.name" -}}
{{- $fullname := include "sie-cluster.fullname" .root }}
{{- printf "%s-worker-%s" $fullname .poolName }}
{{- end }}

{{/*
Worker Service name (headless service for StatefulSet)
*/}}
{{- define "sie-cluster.worker.serviceName" -}}
{{- $fullname := include "sie-cluster.fullname" . }}
{{- printf "%s-worker" $fullname }}
{{- end }}

{{/*
Gateway service name (used for worker discovery)
*/}}
{{- define "sie-cluster.gateway.serviceName" -}}
{{- $fullname := include "sie-cluster.fullname" . }}
{{- printf "%s-gateway" $fullname }}
{{- end }}

{{/*
Gateway metrics service name (ClusterIP-only ServiceMonitor scrape target)
Budget: prefix (≤47) + "-gateway-metrics" (16) = 63 (DNS-1123 label max).
*/}}
{{- define "sie-cluster.gateway.metricsServiceName" -}}
{{- printf "%s-gateway-metrics" (include "sie-cluster.fullname" . | trunc 47 | trimSuffix "-") }}
{{- end }}

{{/*
In-cluster URL used by workers to ask the gateway whether they are admitted
to pull from their configured queue pool.
*/}}
{{- define "sie-cluster.gateway.internalUrl" -}}
{{- $svc := include "sie-cluster.gateway.serviceName" . }}
{{- $ns := include "sie-cluster.namespace" . }}
{{- $port := .Values.gateway.service.port | default 8080 }}
{{- printf "http://%s.%s.svc.cluster.local:%v" $svc $ns $port }}
{{- end }}

{{/*
OAuth2 proxy service name
*/}}
{{- define "sie-cluster.oauth2Proxy.serviceName" -}}
{{- $fullname := include "sie-cluster.fullname" . }}
{{- printf "%s-oauth2-proxy" $fullname }}
{{- end }}

{{/*
Image pull secrets
*/}}
{{- define "sie-cluster.imagePullSecrets" -}}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Health gate hook: Prometheus readiness SA name
*/}}
{{- define "sie-cluster.healthGate.prometheus.serviceAccountName" -}}
{{- printf "%s-health-prometheus" (include "sie-cluster.fullname" . | trunc 45 | trimSuffix "-") }}
{{- end }}

{{/*
Health gate hook: ScaledObject readiness SA name
*/}}
{{- define "sie-cluster.healthGate.scaledobject.serviceAccountName" -}}
{{- printf "%s-health-scaledobject" (include "sie-cluster.fullname" . | trunc 43 | trimSuffix "-") }}
{{- end }}

{{/*
Health gate hook: Gateway readiness SA name
*/}}
{{- define "sie-cluster.healthGate.gateway.serviceAccountName" -}}
{{- printf "%s-health-gateway" (include "sie-cluster.fullname" . | trunc 49 | trimSuffix "-") }}
{{- end }}

{{/*
Health gate hook: Config readiness SA name.
Budget: prefix (≤49) + "-health-config" (14) = 63 (DNS-1123 label max).
*/}}
{{- define "sie-cluster.healthGate.config.serviceAccountName" -}}
{{- printf "%s-health-config" (include "sie-cluster.fullname" . | trunc 49 | trimSuffix "-") }}
{{- end }}

{{/*
Pre-install hook: cert-manager conflict-check SA name.
Budget: prefix (≤45) + "-cm-conflict-check" (18) = 63 (DNS-1123 label max).
*/}}
{{- define "sie-cluster.certManagerConflict.serviceAccountName" -}}
{{- printf "%s-cm-conflict-check" (include "sie-cluster.fullname" . | trunc 45 | trimSuffix "-") }}
{{- end }}

{{/*
Validation: NATS install/enabled consistency.
Fails if nats.install=true but nats.enabled=false (NATS deploys but nothing connects).
*/}}
{{- define "sie-cluster.validateNats" -}}
{{- if and .Values.nats.install (not .Values.nats.enabled) }}
{{- fail "Invalid configuration: nats.install=true but nats.enabled=false. NATS will be deployed but nothing will connect to it. Set nats.enabled=true or nats.install=false." }}
{{- end }}
{{- if and (not .Values.nats.install) .Values.nats.enabled (not .Values.nats.url) }}
{{- fail "Invalid configuration: nats.enabled=true but nats.install=false and nats.url is empty. Either set nats.install=true for in-cluster NATS, or provide nats.url for an external NATS server." }}
{{- end }}
{{- end }}

{{/*
Effective ingress hostnames as a JSON array.
Prefers the list `ingress.hosts`; falls back to the singular `ingress.host`
(backward compatible). Empty array => host-less catch-all ingress.
Consume with: include "sie-cluster.ingress.hosts" . | fromJsonArray
*/}}
{{- define "sie-cluster.ingress.hosts" -}}
{{- $hosts := list -}}
{{- if .Values.ingress.hosts -}}
{{- range .Values.ingress.hosts -}}
{{- $h := trim . -}}
{{- if $h -}}
{{- $hosts = append $hosts $h -}}
{{- end -}}
{{- end -}}
{{- else if .Values.ingress.host -}}
{{- $h := trim .Values.ingress.host -}}
{{- if $h -}}
{{- $hosts = list $h -}}
{{- end -}}
{{- end -}}
{{- $hosts | toJson -}}
{{- end -}}

{{/*
Validation: TLS / cert-manager / trust-manager configuration consistency.
Runs from NOTES.txt so every install/upgrade is checked, regardless of which (or no) Issuer template renders.
*/}}
{{- define "sie-cluster.ingressTlsConfig" -}}
{{- $tls := deepCopy (default (dict) .Values.ingress.tlsConfig) -}}
{{- if and (hasKey .Values.ingress "tls") (kindIs "map" .Values.ingress.tls) -}}
{{- $legacy := .Values.ingress.tls -}}
{{- $legacyActive := or (default false $legacy.enabled) (and (hasKey $legacy "mode") (ne (default "byo" $legacy.mode) "byo")) -}}
{{- if and (not (default false $tls.enabled)) $legacyActive -}}
{{- $tls = mergeOverwrite $tls $legacy -}}
{{- else -}}
{{- $tls = mergeOverwrite (deepCopy $legacy) $tls -}}
{{- end -}}
{{- end -}}
{{- toYaml $tls -}}
{{- end }}

{{- define "sie-cluster.validateTls" -}}
{{- $tls := include "sie-cluster.ingressTlsConfig" . | fromYaml }}
{{- $hosts := include "sie-cluster.ingress.hosts" . | fromJsonArray }}
{{- /* CRD existence is no longer a reliable "is cert-manager installed" signal — we vendor the
       cert-manager and trust-manager CRDs under crds/, so the CRD lands on every install regardless
       of whether a cert-manager Deployment exists. Helm's lookup() can't filter by label, so we
       enumerate every Deployment cluster-wide (lookup with empty namespace = all namespaces) and
       match any whose `app.kubernetes.io/name` label is "cert-manager" / "trust-manager". That
       catches the standard `helm install cert-manager` release name, non-standard names like
       `cert-manager-upstream`, AND installs in unconventional namespaces. Empty under
       `helm template` / `--dry-run`; the pre-install Job hook is the real safety net at apply
       time. */ -}}
{{- $cmDeploy := "" }}
{{- $tmDeploy := "" }}
{{- range $d := (lookup "apps/v1" "Deployment" "" "").items }}
{{- /* Deployments without any labels return metadata.labels=nil; `index nil` errors
       ("index of untyped nil"), unlike `index <map> <missing-key>` which yields "".
       Default to an empty dict so the probe simply skips unlabeled deployments. */ -}}
{{- $labels := $d.metadata.labels | default dict }}
{{- $name := index $labels "app.kubernetes.io/name" }}
{{- if eq $name "cert-manager" }}{{- $cmDeploy = $d }}{{- end }}
{{- if eq $name "trust-manager" }}{{- $tmDeploy = $d }}{{- end }}
{{- end }}
{{- $cmInstall := .Values.certManagerBundle.certManager.install }}
{{- $tmInstall := .Values.certManagerBundle.trustManager.install }}
{{- if $cmInstall }}
{{- if and $cmDeploy (not .Values.certManagerBundle.allowExistingCRDs) }}
{{- fail "Refusing to install bundled cert-manager: a cert-manager Deployment already exists in the cluster. Two cert-manager controllers reconciling the same CRDs will corrupt issuance state. Remediation: (a) set certManagerBundle.certManager.install=false and use ingress.tlsConfig.mode=cert-manager against the existing install, OR (b) uninstall the existing cert-manager first, OR (c) set certManagerBundle.allowExistingCRDs=true (DANGEROUS — only if you understand the consequences)." }}
{{- end }}
{{- end }}
{{- /* Note: we deliberately do NOT fail here when (mode=self-signed | trustManager.install=true |
       trustBundle.enabled=true) is set but no cert-manager is found via lookup. helm template
       intentionally returns empty for lookup(), so a fail here would false-positive every preview
       render against a cluster that does have an external cert-manager. The runtime conflict-check
       Job hook is the authoritative apply-time check; if cert-manager truly isn't present at apply
       time, the cert-manager.io / trust.cert-manager.io resources will fail to reconcile and
       surface in `kubectl get certificate`. */ -}}
{{- if $tls.enabled }}
{{- $mode := default "byo" $tls.mode }}
{{- if not (or (eq $mode "byo") (eq $mode "cert-manager") (eq $mode "self-signed") (eq $mode "disabled")) }}
{{- fail (printf "Invalid configuration: ingress.tlsConfig.mode=%q. Must be one of: \"byo\", \"cert-manager\", \"self-signed\", \"disabled\"." $mode) }}
{{- end }}
{{- if eq $mode "cert-manager" }}
{{- /* The MCP edge ingress (mcpEdge.ingress.host) is its own cert-manager-issued host on
       its own TLS secret, independent of the gateway ingress — so its hostname also
       satisfies this "cert-manager needs something to issue against" check. This lets the
       with-domain edge connector path enable cert-manager without forcing a global
       ingress.host (which would collide gateway + edge on the same host/path). */ -}}
{{- $mcpEdge := default (dict) .Values.mcpEdge }}
{{- $mcpEdgeIngress := default (dict) $mcpEdge.ingress }}
{{- $edgeHost := and $mcpEdge.enabled $mcpEdgeIngress.enabled (trim (default "" $mcpEdgeIngress.host)) }}
{{- if and (not $hosts) (not $edgeHost) }}
{{- fail "Invalid configuration: ingress.tlsConfig.mode=cert-manager requires ingress.host or ingress.hosts (gateway) or mcpEdge.ingress.host (MCP edge) to be set (cert-manager has nothing to issue a certificate against without a hostname)." }}
{{- end }}
{{- $certManager := default (dict) $tls.certManager }}
{{- $kind := default "" $certManager.kind }}
{{- if not (or (eq $kind "ClusterIssuer") (eq $kind "Issuer")) }}
{{- fail (printf "Invalid configuration: ingress.tlsConfig.certManager.kind=%q. Must be either \"ClusterIssuer\" or \"Issuer\" (case-sensitive)." $kind) }}
{{- end }}
{{- if $certManager.create }}
{{- if not $certManager.server }}
{{- fail "Invalid configuration: ingress.tlsConfig.certManager.create=true requires ingress.tlsConfig.certManager.server to be set (ACME directory URL is required)." }}
{{- end }}
{{- if not $certManager.privateKeySecretRef }}
{{- fail "Invalid configuration: ingress.tlsConfig.certManager.create=true requires ingress.tlsConfig.certManager.privateKeySecretRef to be set (ACME account key Secret name is required)." }}
{{- end }}
{{- if not $certManager.email }}
{{- fail "Invalid configuration: ingress.tlsConfig.certManager.create=true requires ingress.tlsConfig.certManager.email to be set (ACME account registration needs an email)." }}
{{- end }}
{{- else }}
{{- if not $certManager.name }}
{{- fail "Invalid configuration: ingress.tlsConfig.certManager.create=false requires ingress.tlsConfig.certManager.name to be set (without a name there is no existing Issuer/ClusterIssuer to annotate against)." }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq $mode "self-signed" }}
{{- $selfSigned := default (dict) $tls.selfSigned }}
{{- $leaf := default (dict) $selfSigned.leaf }}
{{- if and (empty $hosts) (empty $leaf.dnsNames) (empty $leaf.ipAddresses) }}
{{- fail "Invalid configuration: ingress.tlsConfig.mode=self-signed requires at least one of ingress.hosts (or ingress.host), ingress.tlsConfig.selfSigned.leaf.dnsNames, or ingress.tlsConfig.selfSigned.leaf.ipAddresses to be set (the leaf certificate needs at least one SAN)." }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{/*
KEDA apply hook: ServiceAccount name
*/}}
{{- define "sie-cluster.keda.apply.serviceAccountName" -}}
{{- printf "%s-keda-apply" (include "sie-cluster.fullname" . | trunc 51 | trimSuffix "-") }}
{{- end }}

{{/*
Resolve the effective payload-store URL.

Resolution order:
  1. .Values.payloadStore.url set explicitly -> use it verbatim.
  2. .Values.workers.common.clusterCache.enabled and .url set -> derive a
     sibling /payloads path at the same bucket/container root. Terraform
     exposes the cache URL as "<scheme>://<bucket-or-container>/models" by
     convention, so the auto-derivation strips a trailing "/models" segment
     before appending "/payloads". The resulting layout is:
       <bucket-or-container>/models/...    weights (managed by sie-admin cache)
       <bucket-or-container>/payloads/...  large work-item refs (managed by gateway)
     These siblings live at the bucket/container root, which is what the
     workload IAM grants are scoped to in all three (AWS, GCP, Azure)
     terraform modules.
  3. Otherwise -> empty string (payload store is off, no env vars rendered).

Supported URL schemes: s3:// (AWS), gs:// (GCP), abfs:// + abfss:// (Azure
Data Lake Storage Gen2 / Blob with hierarchical namespace enabled). The
Azure scheme variant is treated identically to the AWS/GCP variants for
the derivation step — the trailing "/models" → "/payloads" swap works
the same way because Azure URLs follow the same
"<scheme>://<container>@<account>.dfs.core.windows.net/<prefix>"
convention exposed by the deploy/terraform/azure module.

Templates that consume this should treat a non-empty result as "payload
store enabled" and an empty result as "off".
*/}}
{{- define "sie-cluster.payloadStoreUrl" -}}
{{- if .Values.payloadStore.enabled -}}
{{- if .Values.payloadStore.url -}}
{{- .Values.payloadStore.url -}}
{{- else if .Values.workers.common.clusterCache.url -}}
{{- $cache := trimSuffix "/" .Values.workers.common.clusterCache.url -}}
{{- $base := trimSuffix "/models" $cache -}}
{{- printf "%s/payloads" $base -}}
{{- end -}}
{{- end -}}
{{- end }}

{{/*
Distinct machine profiles serving a bundle within a queue pool.

Drives the KEDA pending_demand trigger's scale-from-zero matcher. When a
gpu-agnostic request (e.g. /v1/chat/completions without an X-SIE-MACHINE-PROFILE
or a model `:profile` suffix) cannot be served, the gateway records pending
demand with an EMPTY machine_profile label, because a multi-profile queue pool
gives it no single cold lane to name (proxy.rs PoolLookup.pending_demand_profile).
A per-lane scaler keyed on machine_profile="<profile>" never sees that demand, so
the lane stays at zero and the model is stuck "provisioning". A lane whose bundle
maps to exactly one machine profile in the pool is unambiguous and can safely also
count the empty-label demand.

Args (dict): root, queuePool, bundle.
Returns a comma-joined, sorted list of distinct machine profiles.
*/}}
{{- define "sie-cluster.bundle.machineProfiles" -}}
{{- $root := .root -}}
{{- $queuePool := .queuePool | lower -}}
{{- $bundle := .bundle -}}
{{- $defaultQueuePool := default "default" $root.Values.workers.common.queuePool | lower -}}
{{- $profiles := dict -}}
{{- range $poolName, $pool := $root.Values.workers.pools -}}
{{- if $pool.enabled -}}
{{- $mp := default $poolName $pool.machineProfile -}}
{{- $qp := default $defaultQueuePool $pool.queuePool | lower -}}
{{- if eq $qp $queuePool -}}
{{- range $bundleName, $bundleCfg := $pool.bundles -}}
{{- if and (eq $bundleName $bundle) (dig "enabled" true $bundleCfg) -}}
{{- $_ := set $profiles $mp true -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- keys $profiles | sortAlpha | join "," -}}
{{- end }}

{{/*
MCP edge (Req 12) — the hosted MCP server fronting the cluster's document jobs.
*/}}
{{- define "sie-cluster.mcpEdge.serviceName" -}}
{{- printf "%s-mcp" (include "sie-cluster.fullname" .) }}
{{- end }}

{{- define "sie-cluster.mcpEdge.labels" -}}
{{ include "sie-cluster.labels" . }}
app.kubernetes.io/component: mcp-edge
{{- end }}

{{- define "sie-cluster.mcpEdge.selectorLabels" -}}
{{ include "sie-cluster.selectorLabels" . }}
app.kubernetes.io/component: mcp-edge
{{- end }}

{{- define "sie-cluster.mcpEdge.image" -}}
{{- $tag := default .Chart.AppVersion .Values.mcpEdge.image.tag }}
{{- printf "%s:%s" .Values.mcpEdge.image.repository $tag }}
{{- end }}

{{/*
Rust Candle worker image tag.

Args (dict): root, poolName, pool, machineProfile.
Returns the tag only. The caller prepends workers.common.rust.image.repository.
*/}}
{{- define "sie-cluster.rustWorker.imageTag" -}}
{{- $root := .root -}}
{{- $poolName := .poolName -}}
{{- $pool := .pool -}}
{{- $machineProfile := .machineProfile -}}
{{- $rustImage := $root.Values.workers.common.rust.image -}}
{{- $fullTag := default "" $rustImage.fullTag -}}
{{- if $fullTag -}}
{{- $fullTag -}}
{{- else -}}
{{- $tagBase := default $root.Chart.AppVersion $rustImage.tag -}}
{{- $gpu := default dict $pool.gpu -}}
{{- $gpuCount := int (default 0 $gpu.count) -}}
{{- if eq $gpuCount 0 -}}
{{- $tagBase -}}
{{- else -}}
{{- $cudaPlatform := default "cuda12" $rustImage.cudaPlatform -}}
{{- $computeCap := default "" $rustImage.computeCapability -}}
{{- $capByProfile := default dict $rustImage.computeCapabilityByMachineProfile -}}
{{- if hasKey $capByProfile $machineProfile -}}
{{- $computeCap = printf "%v" (index $capByProfile $machineProfile) -}}
{{- end -}}
{{- if and $pool.gpuType (hasKey $capByProfile $pool.gpuType) -}}
{{- $computeCap = printf "%v" (index $capByProfile $pool.gpuType) -}}
{{- end -}}
{{- if hasKey $capByProfile $poolName -}}
{{- $computeCap = printf "%v" (index $capByProfile $poolName) -}}
{{- end -}}
{{- $poolCandle := default dict $pool.candle -}}
{{- if $poolCandle.cudaComputeCap -}}
{{- $computeCap = printf "%v" $poolCandle.cudaComputeCap -}}
{{- end -}}
{{- if not $computeCap -}}
{{- fail (printf "workers.pools.%s.engine=candle needs a Rust CUDA compute capability. Set workers.common.rust.image.computeCapabilityByMachineProfile[%q], workers.common.rust.image.computeCapability, or workers.pools.%s.candle.cudaComputeCap." $poolName $machineProfile $poolName) -}}
{{- end -}}
{{- printf "%s-%s-sm%s" $tagBase $cudaPlatform $computeCap -}}
{{- end -}}
{{- end -}}
{{- end }}

{{/*
In-cluster URL the edge uses to reach the gateway (SIE_BASE_URL). Overridable
via mcpEdge.clusterBaseUrl; otherwise the in-namespace gateway Service.
*/}}
{{- define "sie-cluster.mcpEdge.clusterBaseUrl" -}}
{{- if .Values.mcpEdge.clusterBaseUrl -}}
{{- .Values.mcpEdge.clusterBaseUrl -}}
{{- else -}}
{{- printf "http://%s:%v" (include "sie-cluster.gateway.serviceName" .) .Values.gateway.service.port -}}
{{- end -}}
{{- end }}

{{/*
Tracing: effective OTLP endpoint.

When the bundled collector is enabled and no explicit endpoint is set, the
endpoint defaults to the bundled collector's in-cluster gRPC address. Otherwise,
bundled Tempo is used when installed. The explicit
.Values.observability.tracing.endpoint always wins (may be empty).

Caller context: root (.) — the full Helm root context.
*/}}
{{- define "sie-cluster.tracing.endpoint" -}}
{{- if .Values.observability.tracing.endpoint -}}
{{- .Values.observability.tracing.endpoint -}}
{{- else if .Values.observability.tracing.collector.install -}}
{{- printf "http://%s-otel-collector:4317" (include "sie-cluster.fullname" .) -}}
{{- else if .Values.observability.tracing.tempo.install -}}
{{- "http://tempo:4317" -}}
{{- else -}}
{{- "" -}}
{{- end -}}
{{- end }}

{{/*
Tracing: effective bundled collector downstream OTLP endpoint.

The collector forwards to an explicit collector exporterEndpoint when set. If
bundled Tempo is installed and no downstream endpoint is configured, the
collector forwards to Tempo. Otherwise it returns empty so the collector debug
exporter is used.

Caller context: root (.) — the full Helm root context.
*/}}
{{- define "sie-cluster.tracing.collectorExporterEndpoint" -}}
{{- if .Values.observability.tracing.collector.exporterEndpoint -}}
{{- .Values.observability.tracing.collector.exporterEndpoint -}}
{{- else if .Values.observability.tracing.tempo.install -}}
{{- "http://tempo:4317" -}}
{{- else -}}
{{- "" -}}
{{- end -}}
{{- end }}

{{/*
Tracing: OTLP exporter env block.

Emits the five OTEL/SIE env vars required to activate distributed tracing on a
container. Fails fast when tracing is enabled but no endpoint is resolvable.

Args (dict): root — full Helm root context; serviceName — OTEL_SERVICE_NAME value.

Rendered lines are indented by the call site (use nindent in the include call).
*/}}
{{- define "sie-cluster.tracing.env" -}}
{{- $endpoint := include "sie-cluster.tracing.endpoint" .root -}}
{{- if not $endpoint -}}
{{- fail "observability.tracing.enabled=true requires observability.tracing.endpoint, observability.tracing.collector.install=true, or observability.tracing.tempo.install=true" -}}
{{- end -}}
- name: SIE_TRACING_ENABLED
  value: "true"
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: {{ $endpoint | quote }}
- name: OTEL_EXPORTER_OTLP_PROTOCOL
  value: "grpc"
- name: OTEL_SERVICE_NAME
  value: {{ .serviceName | quote }}
- name: OTEL_TRACES_SAMPLER
  value: {{ .root.Values.observability.tracing.sampler | quote }}
- name: OTEL_TRACES_SAMPLER_ARG
  value: {{ .root.Values.observability.tracing.samplerArg | quote }}
{{- end }}

{{/*
Name of the Secret holding the connector secrets. Uses an existing Secret when
mcpEdge.existingSecretName is set; otherwise the chart-managed one.
*/}}
{{- define "sie-cluster.mcpEdge.secretName" -}}
{{- if .Values.mcpEdge.existingSecretName -}}
{{- .Values.mcpEdge.existingSecretName -}}
{{- else -}}
{{- printf "%s-connector-secrets" (include "sie-cluster.mcpEdge.serviceName" .) -}}
{{- end -}}
{{- end }}
